<a href="https://colab.research.google.com/github/Nagmashaik123/Section203-Group06/blob/main/Concatinate_tweets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# We have fetched 10000 records per one user API request. 
# Called 
# Concatinating them to one single file as #CovidVaccine.csv

import os
import glob
import pandas as pd
os.chdir("/content")

extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

#combine all files in the list
dataFrame = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
dataFrame.to_csv( "CovidVaccineWorldWide.csv", index=False, encoding='utf-8-sig')
dataFrame

     Unnamed: 0  ...         Country
0             0  ...         Unknown
1             1  ...   United States
2             2  ...         Unknown
3             3  ...          Brazil
4             4  ...         Romania
...         ...  ...             ...
9995       9995  ...         Unknown
9996       9996  ...         Unknown
9997       9997  ...          Turkey
9998       9998  ...           Kenya
9999       9999  ...  United Kingdom

[206250 rows x 7 columns]